/*
 * Broker API
 * Broker APIs provide access to Kimono Broker resources and operations
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.broker;

import kimono.api.v2.broker.ApiException;
import kimono.api.v2.broker.model.ErrorType;
import kimono.api.v2.broker.model.Model;
import kimono.api.v2.broker.model.ModelsResponse;
import kimono.api.v2.broker.model.VocabularysResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for VocabularyApi
 */
@Ignore
public class VocabularyApiTest {

    private final VocabularyApi api = new VocabularyApi();

    
    /**
     * Create Data Models
     *
     * Create a Data Model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createModelTest() throws ApiException {
        ModelsResponse response = api.createModel();

        // TODO: test validations
    }
    
    /**
     * Delete a Data Model
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteModelTest() throws ApiException {
        java.util.UUID id = null;
        api.deleteModel(id);

        // TODO: test validations
    }
    
    /**
     * Get a Data Model by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findModelTest() throws ApiException {
        java.util.UUID id = null;
        Model response = api.findModel(id);

        // TODO: test validations
    }
    
    /**
     * Get a Vocabulary by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findVocabularyTest() throws ApiException {
        java.util.UUID id = null;
        ModelsResponse response = api.findVocabulary(id);

        // TODO: test validations
    }
    
    /**
     * List Data Models
     *
     * Get a list of all defined Data Models
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listModelsTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        ModelsResponse response = api.listModels(page, pageSize);

        // TODO: test validations
    }
    
    /**
     * List Vocabularies
     *
     * Get a list of all defined Vocabularies
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listVocabulariesTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        VocabularysResponse response = api.listVocabularies(page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Update the properties of a Data Model
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateModelTest() throws ApiException {
        java.util.UUID id = null;
        Model response = api.updateModel(id);

        // TODO: test validations
    }
    
    /**
     * Update the properties of a Vocabulary
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateVocabularyTest() throws ApiException {
        java.util.UUID id = null;
        VocabularysResponse response = api.updateVocabulary(id);

        // TODO: test validations
    }
    
}
