/*
 * SIF Cloud API
 * SIF Cloud APIs provide access to SIF Cloud provisioning resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.sifcloud;

import kimono.api.v2.sifcloud.ApiException;
import kimono.api.v2.sifcloud.model.SIFClient;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for ClientsApi
 */
@Ignore
public class ClientsApiTest {

    private final ClientsApi api = new ClientsApi();

    
    /**
     * Get SIF Clients
     *
     * Get a list of &#x60;SIFClient&#x60;s
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listClientsTest() throws ApiException {
        java.util.List<SIFClient> response = api.listClients();

        // TODO: test validations
    }
    
}
