/*
 * Interop API
 * Interop APIs provide access to Kimono Interop Cloud resources and operations
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.interop;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.junit.Ignore;
import org.junit.Test;

import kimono.api.v2.interop.model.TenantInfosResponse;


/**
 * API tests for TenantsApi
 */
@Ignore
public class TenantsApiTest {

    private final TenantsApi api = new TenantsApi();

    
    /**
     * List Interop Tenants
     *
     * Get a list of &#x60;TenantInfo&#x60; representing your licensed and authorized Integration tenants.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listInteropTenantsTest() throws ApiException {
        List<UUID> accounts = Arrays.asList(null);
        List<String> integrations = Arrays.asList();
        TenantInfosResponse response = api.listInteropTenants(accounts, integrations, null, null);

        // TODO: test validations
    }
    
}
