/*
 * Interop API
 * Interop APIs provide access to Kimono Interop Cloud resources and operations
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.interop;

import kimono.api.v2.interop.ApiException;
import kimono.api.v2.interop.model.TenantInfo;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for TenantsApi
 */
@Ignore
public class TenantsApiTest {

    private final TenantsApi api = new TenantsApi();

    
    /**
     * List Interop Tenants
     *
     * Get a list of &#x60;TenantInfo&#x60; representing your licensed and authorized Integration tenants.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listInteropTenantsTest() throws ApiException {
        java.util.List<String> integration = null;
        java.util.List<TenantInfo> response = api.listInteropTenants(integration);

        // TODO: test validations
    }
    
}
