/*
 * Interop Data API
 * Interop Data APIs provide access to the data objects and events from Interop Cloud repositories and Integration repositories
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.interopdata;

import org.junit.Ignore;
import org.junit.Test;

import kimono.api.v2.interopdata.model.TaskAck;
import kimono.api.v2.interopdata.model.TasksResponse;


/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    
    /**
     * Acknowledge Task
     *
     * Each Task that is returned from &#x60;listTasks&#x60; must be acknowledged to remove it from the Task Queue. If a Task is not acknowledged in a timely fashion Kimono may consider it to have timed-out and will return it in the next &#x60;listTasks&#x60; response for an Integration tenant. See [Tasks](doc:interop-data-api-tasks) for details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void acknowledgeTaskTest() throws ApiException {
        java.util.UUID id = null;
        TaskAck taskAck = null;
        api.acknowledgeTask(id, taskAck);

        // TODO: test validations
    }
    
    /**
     * List Tasks
     *
     * Get the next batch of Tasks for the authenticated actor. The number of Tasks returned is determined by Kimono and may change from time to time. See [Tasks](doc:interop-data-api-tasks) for details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTasksTest() throws ApiException {
        TasksResponse response = api.listTasks(null, null);

        // TODO: test validations
    }
    
}
