/*
 * Grades Exchange API
 * Use the Grades Exchange APIs to implement a Grades Producer or Grades Consumer client application and to manage Exchanges between producers and consumers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.grades.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import kimono.api.v2.grades.model.AssignmentScore;
import kimono.api.v2.grades.model.AssignmentSys;
import kimono.api.v2.grades.model.GradesCategoryRefType;
import kimono.api.v2.grades.model.GradesRefType;

/**
 * Assignment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-10T10:16:28.234-06:00[America/Denver]")
public class Assignment {
  public static final String SERIALIZED_NAME_$_SYS = "$sys";
  @SerializedName(SERIALIZED_NAME_$_SYS)
  private AssignmentSys $sys = null;

  public static final String SERIALIZED_NAME_$_SECTION = "$section";
  @SerializedName(SERIALIZED_NAME_$_SECTION)
  private GradesRefType $section = null;

  public static final String SERIALIZED_NAME_$_CATEGORY = "$category";
  @SerializedName(SERIALIZED_NAME_$_CATEGORY)
  private GradesCategoryRefType $category = null;

  public static final String SERIALIZED_NAME_$_TERM = "$term";
  @SerializedName(SERIALIZED_NAME_$_TERM)
  private GradesRefType $term = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_POINTS_POSSIBLE = "points_possible";
  @SerializedName(SERIALIZED_NAME_POINTS_POSSIBLE)
  private BigDecimal pointsPossible;

  public static final String SERIALIZED_NAME_DUE_AT = "due_at";
  @SerializedName(SERIALIZED_NAME_DUE_AT)
  private OffsetDateTime dueAt;

  public static final String SERIALIZED_NAME_AVAILABLE_AT = "available_at";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_AT)
  private OffsetDateTime availableAt;

  public static final String SERIALIZED_NAME_$_EXT = "$ext";
  @SerializedName(SERIALIZED_NAME_$_EXT)
  private java.util.Map<String, String> $ext = null;

  public static final String SERIALIZED_NAME_SCORES = "scores";
  @SerializedName(SERIALIZED_NAME_SCORES)
  private java.util.List<AssignmentScore> scores = null;

  public Assignment $sys(AssignmentSys $sys) {
    this.$sys = $sys;
    return this;
  }

   /**
   * Get $sys
   * @return $sys
  **/
  @ApiModelProperty(value = "")
  public AssignmentSys get$Sys() {
    return $sys;
  }

  public void set$Sys(AssignmentSys $sys) {
    this.$sys = $sys;
  }

  public Assignment $section(GradesRefType $section) {
    this.$section = $section;
    return this;
  }

   /**
   * Get $section
   * @return $section
  **/
  @ApiModelProperty(value = "")
  public GradesRefType get$Section() {
    return $section;
  }

  public void set$Section(GradesRefType $section) {
    this.$section = $section;
  }

  public Assignment $category(GradesCategoryRefType $category) {
    this.$category = $category;
    return this;
  }

   /**
   * Get $category
   * @return $category
  **/
  @ApiModelProperty(value = "")
  public GradesCategoryRefType get$Category() {
    return $category;
  }

  public void set$Category(GradesCategoryRefType $category) {
    this.$category = $category;
  }

  public Assignment $term(GradesRefType $term) {
    this.$term = $term;
    return this;
  }

   /**
   * Get $term
   * @return $term
  **/
  @ApiModelProperty(value = "")
  public GradesRefType get$Term() {
    return $term;
  }

  public void set$Term(GradesRefType $term) {
    this.$term = $term;
  }

  public Assignment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Assignment description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Assignment pointsPossible(BigDecimal pointsPossible) {
    this.pointsPossible = pointsPossible;
    return this;
  }

   /**
   * Get pointsPossible
   * @return pointsPossible
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPointsPossible() {
    return pointsPossible;
  }

  public void setPointsPossible(BigDecimal pointsPossible) {
    this.pointsPossible = pointsPossible;
  }

  public Assignment dueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
    return this;
  }

   /**
   * Get dueAt
   * @return dueAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDueAt() {
    return dueAt;
  }

  public void setDueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
  }

  public Assignment availableAt(OffsetDateTime availableAt) {
    this.availableAt = availableAt;
    return this;
  }

   /**
   * Get availableAt
   * @return availableAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAvailableAt() {
    return availableAt;
  }

  public void setAvailableAt(OffsetDateTime availableAt) {
    this.availableAt = availableAt;
  }

  public Assignment $ext(java.util.Map<String, String> $ext) {
    this.$ext = $ext;
    return this;
  }

  public Assignment put$ExtItem(String key, String $extItem) {
    if (this.$ext == null) {
      this.$ext = new java.util.HashMap<>();
    }
    this.$ext.put(key, $extItem);
    return this;
  }

   /**
   * Get $ext
   * @return $ext
  **/
  @ApiModelProperty(value = "")
  public java.util.Map<String, String> get$Ext() {
    return $ext;
  }

  public void set$Ext(java.util.Map<String, String> $ext) {
    this.$ext = $ext;
  }

  public Assignment scores(java.util.List<AssignmentScore> scores) {
    this.scores = scores;
    return this;
  }

  public Assignment addScoresItem(AssignmentScore scoresItem) {
    if (this.scores == null) {
      this.scores = new java.util.ArrayList<>();
    }
    this.scores.add(scoresItem);
    return this;
  }

   /**
   * Get scores
   * @return scores
  **/
  @ApiModelProperty(value = "")
  public java.util.List<AssignmentScore> getScores() {
    return scores;
  }

  public void setScores(java.util.List<AssignmentScore> scores) {
    this.scores = scores;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assignment assignment = (Assignment) o;
    return Objects.equals(this.$sys, assignment.$sys) &&
        Objects.equals(this.$section, assignment.$section) &&
        Objects.equals(this.$category, assignment.$category) &&
        Objects.equals(this.$term, assignment.$term) &&
        Objects.equals(this.name, assignment.name) &&
        Objects.equals(this.description, assignment.description) &&
        Objects.equals(this.pointsPossible, assignment.pointsPossible) &&
        Objects.equals(this.dueAt, assignment.dueAt) &&
        Objects.equals(this.availableAt, assignment.availableAt) &&
        Objects.equals(this.$ext, assignment.$ext) &&
        Objects.equals(this.scores, assignment.scores);
  }

  @Override
  public int hashCode() {
    return Objects.hash($sys, $section, $category, $term, name, description, pointsPossible, dueAt, availableAt, $ext, scores);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assignment {\n");
    
    sb.append("    $sys: ").append(toIndentedString($sys)).append("\n");
    sb.append("    $section: ").append(toIndentedString($section)).append("\n");
    sb.append("    $category: ").append(toIndentedString($category)).append("\n");
    sb.append("    $term: ").append(toIndentedString($term)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    pointsPossible: ").append(toIndentedString(pointsPossible)).append("\n");
    sb.append("    dueAt: ").append(toIndentedString(dueAt)).append("\n");
    sb.append("    availableAt: ").append(toIndentedString(availableAt)).append("\n");
    sb.append("    $ext: ").append(toIndentedString($ext)).append("\n");
    sb.append("    scores: ").append(toIndentedString(scores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

