/*
 * Platform API
 * Platform APIs provide access to core Kimono Platform resources and operations such as Accounts, Users, and Clouds.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.platform.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
