/*
 * Interop Data API
 * Interop Data APIs provide access to the data objects and events from Interop Cloud repositories and Integration repositories
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.interopdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import kimono.api.v2.interopdata.model.AddressType;
import kimono.api.v2.interopdata.model.NameType;
import kimono.api.v2.interopdata.model.ObjectType;
import kimono.api.v2.interopdata.model.OrgSysType;
import kimono.api.v2.interopdata.model.PersonSysType;
import kimono.api.v2.interopdata.model.SysType;

/**
 * Person
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-20T10:02:09.090-06:00[America/Denver]")
public class Person extends ObjectType {
  public static final String SERIALIZED_NAME_$_SYS = "$sys";
  @SerializedName(SERIALIZED_NAME_$_SYS)
  private PersonSysType $sys = null;

  public static final String SERIALIZED_NAME_LOCAL_ID = "local_id";
  @SerializedName(SERIALIZED_NAME_LOCAL_ID)
  private String localId;

  public static final String SERIALIZED_NAME_STATE_ID = "state_id";
  @SerializedName(SERIALIZED_NAME_STATE_ID)
  private String stateId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private NameType name = null;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private AddressType address = null;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_SEX = "sex";
  @SerializedName(SERIALIZED_NAME_SEX)
  private String sex;

  public static final String SERIALIZED_NAME_DOB = "dob";
  @SerializedName(SERIALIZED_NAME_DOB)
  private LocalDate dob;

  public static final String SERIALIZED_NAME_AUP = "aup";
  @SerializedName(SERIALIZED_NAME_AUP)
  private Boolean aup;

  public static final String SERIALIZED_NAME_GRAD_YEAR = "grad_year";
  @SerializedName(SERIALIZED_NAME_GRAD_YEAR)
  private String gradYear;

  public static final String SERIALIZED_NAME_$_SCHOOLS = "$schools";
  @SerializedName(SERIALIZED_NAME_$_SCHOOLS)
  private java.util.List<OrgSysType> $schools = null;

  public static final String SERIALIZED_NAME_$_SECTIONS = "$sections";
  @SerializedName(SERIALIZED_NAME_$_SECTIONS)
  private java.util.List<SysType> $sections = null;

  public Person $sys(PersonSysType $sys) {
    this.$sys = $sys;
    return this;
  }

   /**
   * Get $sys
   * @return $sys
  **/
  @ApiModelProperty(required = true, value = "")
  public PersonSysType get$Sys() {
    return $sys;
  }

  public void set$Sys(PersonSysType $sys) {
    this.$sys = $sys;
  }

   /**
   * Get localId
   * @return localId
  **/
  @ApiModelProperty(value = "")
  public String getLocalId() {
    return localId;
  }

   /**
   * Get stateId
   * @return stateId
  **/
  @ApiModelProperty(value = "")
  public String getStateId() {
    return stateId;
  }

  public Person name(NameType name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public NameType getName() {
    return name;
  }

  public void setName(NameType name) {
    this.name = name;
  }

  public Person address(AddressType address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressType getAddress() {
    return address;
  }

  public void setAddress(AddressType address) {
    this.address = address;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

   /**
   * Get sex
   * @return sex
  **/
  @ApiModelProperty(value = "")
  public String getSex() {
    return sex;
  }

   /**
   * Get dob
   * @return dob
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDob() {
    return dob;
  }

   /**
   * Get aup
   * @return aup
  **/
  @ApiModelProperty(value = "")
  public Boolean getAup() {
    return aup;
  }

   /**
   * Get gradYear
   * @return gradYear
  **/
  @ApiModelProperty(value = "")
  public String getGradYear() {
    return gradYear;
  }

   /**
   * Get $schools
   * @return $schools
  **/
  @ApiModelProperty(value = "")
  public java.util.List<OrgSysType> get$Schools() {
    return $schools;
  }

   /**
   * Get $sections
   * @return $sections
  **/
  @ApiModelProperty(value = "")
  public java.util.List<SysType> get$Sections() {
    return $sections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.$sys, person.$sys) &&
        Objects.equals(this.localId, person.localId) &&
        Objects.equals(this.stateId, person.stateId) &&
        Objects.equals(this.name, person.name) &&
        Objects.equals(this.address, person.address) &&
        Objects.equals(this.phone, person.phone) &&
        Objects.equals(this.email, person.email) &&
        Objects.equals(this.sex, person.sex) &&
        Objects.equals(this.dob, person.dob) &&
        Objects.equals(this.aup, person.aup) &&
        Objects.equals(this.gradYear, person.gradYear) &&
        Objects.equals(this.$schools, person.$schools) &&
        Objects.equals(this.$sections, person.$sections) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash($sys, localId, stateId, name, address, phone, email, sex, dob, aup, gradYear, $schools, $sections, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    $sys: ").append(toIndentedString($sys)).append("\n");
    sb.append("    localId: ").append(toIndentedString(localId)).append("\n");
    sb.append("    stateId: ").append(toIndentedString(stateId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    aup: ").append(toIndentedString(aup)).append("\n");
    sb.append("    gradYear: ").append(toIndentedString(gradYear)).append("\n");
    sb.append("    $schools: ").append(toIndentedString($schools)).append("\n");
    sb.append("    $sections: ").append(toIndentedString($sections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

