/*
 * Platform API
 * Platform APIs provide access to core Kimono Platform resources and operations such as Accounts, Users, and Clouds.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kimono.api.v2.platform.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AccountStatus
 */
@JsonAdapter(AccountStatus.Adapter.class)
public enum AccountStatus {
  
  PENDING_ACTIVATION("pending_activation"),
  
  ACTIVE("active"),
  
  SUSPENDED_MAINTENANCE("suspended_maintenance"),
  
  SUSPENDED_LICENSING("suspended_licensing"),
  
  SUSPENDED_PAYMENT("suspended_payment"),
  
  SUSPENDED_USAGE("suspended_usage"),
  
  SUSPENDED_TRANSFERRING("suspended_transferring"),
  
  CLOSED("closed");

  private String value;

  AccountStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccountStatus fromValue(String text) {
    for (AccountStatus b : AccountStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }

  public static class Adapter extends TypeAdapter<AccountStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccountStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccountStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccountStatus.fromValue(String.valueOf(value));
    }
  }
}

